const MULTICHAIN_BURN_PROGRAM_SOLANA_ADDRESS = import.meta.env
    .VITE_MULTIBURN_PROGRAM_CONTRACT_SOLANA;
const MULTICHAIN_BURN_PROGRAM_EVM_FACTORY_SWAP_ADDRESS = import.meta.env
    .VITE_MULTIBURN_PROGRAM_CONTRACT_EVM_FACTORY_SWAP;
const MULTICHAIN_BURN_PROGRAM_EVM_ROUTER_SWAP_ADDRESS = import.meta.env
    .VITE_MULTIBURN_PROGRAM_CONTRACT_EVM_ROUTER_SWAP;
const MULTICHAIN_BURN_PROGRAM_EVM_FACTORY_BURN_ADDRESS = import.meta.env
    .VITE_MULTIBURN_PROGRAM_CONTRACT_EVM_FACTORY_BURN;
const MULTICHAIN_BURN_PROGRAM_EVM_ROUTER_BURN_ADDRESS = import.meta.env
    .VITE_MULTIBURN_PROGRAM_CONTRACT_EVM_ROUTER_BURN;

export {
    MULTICHAIN_BURN_PROGRAM_SOLANA_ADDRESS,
    MULTICHAIN_BURN_PROGRAM_EVM_FACTORY_SWAP_ADDRESS,
    MULTICHAIN_BURN_PROGRAM_EVM_ROUTER_SWAP_ADDRESS,
    MULTICHAIN_BURN_PROGRAM_EVM_FACTORY_BURN_ADDRESS,
    MULTICHAIN_BURN_PROGRAM_EVM_ROUTER_BURN_ADDRESS,
};
