const MULTICHAIN_BURN_PROGRAM_SOLANA_ADDRESS = import.meta.env
    .VITE_MULTIBURN_PROGRAM_CONTRACT_SOLANA;
const MULTICHAIN_BURN_PROGRAM_EVM_ADDRESS = import.meta.env
    .VITE_MULTIBURN_PROGRAM_CONTRACT_EVM;
const MULTICHAIN_BURN_PROGRAM_EVM_ROUTER_ADDRESS = import.meta.env
    .VITE_MULTIBURN_PROGRAM_CONTRACT_EVM_ROUTER;

export {
    MULTICHAIN_BURN_PROGRAM_SOLANA_ADDRESS,
    MULTICHAIN_BURN_PROGRAM_EVM_ADDRESS,
    MULTICHAIN_BURN_PROGRAM_EVM_ROUTER_ADDRESS,
};
