const MULTICHAIN_BURN_PROGRAM_SOLANA_ADDRESS = import.meta.env
    .VITE_MULTIBURN_PROGRAM_CONTRACT_SOLANA;
const MULTICHAIN_BURN_PROGRAM_EVM_FACTORY_SWAP_ADDRESS = import.meta.env
    .VITE_MULTIBURN_PROGRAM_CONTRACT_EVM_FACTORY_SWAP;
const MULTICHAIN_BURN_PROGRAM_EVM_ROUTER_SWAP_ADDRESS = import.meta.env
    .VITE_MULTIBURN_PROGRAM_CONTRACT_EVM_ROUTER_SWAP;
const MULTICHAIN_BURN_PROGRAM_EVM_FACTORY_BURN_ADDRESS = import.meta.env
    .VITE_MULTIBURN_PROGRAM_CONTRACT_EVM_FACTORY_BURN;
const MULTICHAIN_BURN_PROGRAM_EVM_ROUTER_BURN_ADDRESS = import.meta.env
    .VITE_MULTIBURN_PROGRAM_CONTRACT_EVM_ROUTER_BURN;
const MULTICHAIN_BURN_PROGRAM_EVM_ACCESS_MANAGER_SWAP_ADDRESS = import.meta.env
    .VITE_MULTIBURN_PROGRAM_CONTRACT_EVM_ACCESS_MANAGER_SWAP;

const MULTICHAIN_BURN_PROGRAM_XPHERE_FACTORY_BURN_ADDRESS = import.meta.env
    .VITE_MULTIBURN_PROGRAM_CONTRACT_XPHERE_FACTORY_BURN;
const MULTICHAIN_BURN_PROGRAM_XPHERE_ROUTER_BURN_ADDRESS = import.meta.env
    .VITE_MULTIBURN_PROGRAM_CONTRACT_XPHERE_ROUTER_BURN;
const MULTICHAIN_BURN_PROGRAM_XPHERE_FACTORY_SWAP_ADDRESS = import.meta.env
    .VITE_MULTIBURN_PROGRAM_CONTRACT_XPHERE_FACTORY_SWAP;
const MULTICHAIN_BURN_PROGRAM_XPHERE_ROUTER_SWAP_ADDRESS = import.meta.env
    .VITE_MULTIBURN_PROGRAM_CONTRACT_XPHERE_ROUTER_SWAP;
const MULTICHAIN_BURN_PROGRAM_XPHERE_ACCESS_MANAGER_SWAP_ADDRESS = import.meta.env
    .VITE_MULTIBURN_PROGRAM_CONTRACT_XPHERE_ACCESS_MANAGER_SWAP;

const MULTICHAIN_BURN_PROGRAM_BSC_FACTORY_BURN_ADDRESS = import.meta.env
    .VITE_MULTIBURN_PROGRAM_CONTRACT_BSC_FACTORY_BURN;
const MULTICHAIN_BURN_PROGRAM_BSC_ROUTER_BURN_ADDRESS = import.meta.env
    .VITE_MULTIBURN_PROGRAM_CONTRACT_BSC_ROUTER_BURN;
const MULTICHAIN_BURN_PROGRAM_BSC_FACTORY_SWAP_ADDRESS = import.meta.env
    .VITE_MULTIBURN_PROGRAM_CONTRACT_BSC_FACTORY_SWAP;
const MULTICHAIN_BURN_PROGRAM_BSC_ROUTER_SWAP_ADDRESS = import.meta.env
    .VITE_MULTIBURN_PROGRAM_CONTRACT_BSC_ROUTER_SWAP;
const MULTICHAIN_BURN_PROGRAM_BSC_ACCESS_MANAGER_SWAP_ADDRESS = import.meta.env
    .VITE_MULTIBURN_PROGRAM_CONTRACT_BSC_ACCESS_MANAGER_SWAP;


export {
    MULTICHAIN_BURN_PROGRAM_SOLANA_ADDRESS,
    MULTICHAIN_BURN_PROGRAM_EVM_FACTORY_SWAP_ADDRESS,
    MULTICHAIN_BURN_PROGRAM_EVM_ROUTER_SWAP_ADDRESS,
    MULTICHAIN_BURN_PROGRAM_EVM_FACTORY_BURN_ADDRESS,
    MULTICHAIN_BURN_PROGRAM_EVM_ROUTER_BURN_ADDRESS,
    MULTICHAIN_BURN_PROGRAM_EVM_ACCESS_MANAGER_SWAP_ADDRESS,
    MULTICHAIN_BURN_PROGRAM_XPHERE_FACTORY_BURN_ADDRESS,
    MULTICHAIN_BURN_PROGRAM_XPHERE_ROUTER_BURN_ADDRESS,
    MULTICHAIN_BURN_PROGRAM_XPHERE_FACTORY_SWAP_ADDRESS,
    MULTICHAIN_BURN_PROGRAM_XPHERE_ROUTER_SWAP_ADDRESS,
    MULTICHAIN_BURN_PROGRAM_XPHERE_ACCESS_MANAGER_SWAP_ADDRESS,
    MULTICHAIN_BURN_PROGRAM_BSC_FACTORY_BURN_ADDRESS,
    MULTICHAIN_BURN_PROGRAM_BSC_ROUTER_BURN_ADDRESS,
    MULTICHAIN_BURN_PROGRAM_BSC_FACTORY_SWAP_ADDRESS,
    MULTICHAIN_BURN_PROGRAM_BSC_ROUTER_SWAP_ADDRESS,
    MULTICHAIN_BURN_PROGRAM_BSC_ACCESS_MANAGER_SWAP_ADDRESS,
};
