/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SwapIndexRouteImport } from './routes/swap/index'
import { Route as SwapHistoryIndexRouteImport } from './routes/swap-history/index'
import { Route as SupportIndexRouteImport } from './routes/support/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as PersonalInfoSettingsIndexRouteImport } from './routes/personal-info-settings/index'
import { Route as PairListIndexRouteImport } from './routes/pair-list/index'
import { Route as MyParticipatedPoolsIndexRouteImport } from './routes/my-participated-pools/index'
import { Route as MyDashboardIndexRouteImport } from './routes/my-dashboard/index'
import { Route as MyCreatePoolsIndexRouteImport } from './routes/my-create-pools/index'
import { Route as BurnIndexRouteImport } from './routes/burn/index'
import { Route as ActivityHistoryIndexRouteImport } from './routes/activity-history/index'
import { Route as AdminWhitelistUserIndexRouteImport } from './routes/admin/whitelist-user/index'
import { Route as AdminWhitelistTokenIndexRouteImport } from './routes/admin/whitelist-token/index'
import { Route as SwapDetailAddressRouteImport } from './routes/swap/detail/$address'
import { Route as BurnDetailAddressRouteImport } from './routes/burn/detail/$address'
import { Route as AdminBurnDetailAddressRouteImport } from './routes/admin/burn/detail/$address'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SwapIndexRoute = SwapIndexRouteImport.update({
  id: '/swap/',
  path: '/swap/',
  getParentRoute: () => rootRouteImport,
} as any)
const SwapHistoryIndexRoute = SwapHistoryIndexRouteImport.update({
  id: '/swap-history/',
  path: '/swap-history/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportIndexRoute = SupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalInfoSettingsIndexRoute =
  PersonalInfoSettingsIndexRouteImport.update({
    id: '/personal-info-settings/',
    path: '/personal-info-settings/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PairListIndexRoute = PairListIndexRouteImport.update({
  id: '/pair-list/',
  path: '/pair-list/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyParticipatedPoolsIndexRoute =
  MyParticipatedPoolsIndexRouteImport.update({
    id: '/my-participated-pools/',
    path: '/my-participated-pools/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MyDashboardIndexRoute = MyDashboardIndexRouteImport.update({
  id: '/my-dashboard/',
  path: '/my-dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCreatePoolsIndexRoute = MyCreatePoolsIndexRouteImport.update({
  id: '/my-create-pools/',
  path: '/my-create-pools/',
  getParentRoute: () => rootRouteImport,
} as any)
const BurnIndexRoute = BurnIndexRouteImport.update({
  id: '/burn/',
  path: '/burn/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityHistoryIndexRoute = ActivityHistoryIndexRouteImport.update({
  id: '/activity-history/',
  path: '/activity-history/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWhitelistUserIndexRoute = AdminWhitelistUserIndexRouteImport.update({
  id: '/admin/whitelist-user/',
  path: '/admin/whitelist-user/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWhitelistTokenIndexRoute =
  AdminWhitelistTokenIndexRouteImport.update({
    id: '/admin/whitelist-token/',
    path: '/admin/whitelist-token/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SwapDetailAddressRoute = SwapDetailAddressRouteImport.update({
  id: '/swap/detail/$address',
  path: '/swap/detail/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const BurnDetailAddressRoute = BurnDetailAddressRouteImport.update({
  id: '/burn/detail/$address',
  path: '/burn/detail/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBurnDetailAddressRoute = AdminBurnDetailAddressRouteImport.update({
  id: '/admin/burn/detail/$address',
  path: '/admin/burn/detail/$address',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity-history': typeof ActivityHistoryIndexRoute
  '/burn': typeof BurnIndexRoute
  '/my-create-pools': typeof MyCreatePoolsIndexRoute
  '/my-dashboard': typeof MyDashboardIndexRoute
  '/my-participated-pools': typeof MyParticipatedPoolsIndexRoute
  '/pair-list': typeof PairListIndexRoute
  '/personal-info-settings': typeof PersonalInfoSettingsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/support': typeof SupportIndexRoute
  '/swap-history': typeof SwapHistoryIndexRoute
  '/swap': typeof SwapIndexRoute
  '/burn/detail/$address': typeof BurnDetailAddressRoute
  '/swap/detail/$address': typeof SwapDetailAddressRoute
  '/admin/whitelist-token': typeof AdminWhitelistTokenIndexRoute
  '/admin/whitelist-user': typeof AdminWhitelistUserIndexRoute
  '/admin/burn/detail/$address': typeof AdminBurnDetailAddressRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity-history': typeof ActivityHistoryIndexRoute
  '/burn': typeof BurnIndexRoute
  '/my-create-pools': typeof MyCreatePoolsIndexRoute
  '/my-dashboard': typeof MyDashboardIndexRoute
  '/my-participated-pools': typeof MyParticipatedPoolsIndexRoute
  '/pair-list': typeof PairListIndexRoute
  '/personal-info-settings': typeof PersonalInfoSettingsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/support': typeof SupportIndexRoute
  '/swap-history': typeof SwapHistoryIndexRoute
  '/swap': typeof SwapIndexRoute
  '/burn/detail/$address': typeof BurnDetailAddressRoute
  '/swap/detail/$address': typeof SwapDetailAddressRoute
  '/admin/whitelist-token': typeof AdminWhitelistTokenIndexRoute
  '/admin/whitelist-user': typeof AdminWhitelistUserIndexRoute
  '/admin/burn/detail/$address': typeof AdminBurnDetailAddressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity-history/': typeof ActivityHistoryIndexRoute
  '/burn/': typeof BurnIndexRoute
  '/my-create-pools/': typeof MyCreatePoolsIndexRoute
  '/my-dashboard/': typeof MyDashboardIndexRoute
  '/my-participated-pools/': typeof MyParticipatedPoolsIndexRoute
  '/pair-list/': typeof PairListIndexRoute
  '/personal-info-settings/': typeof PersonalInfoSettingsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/support/': typeof SupportIndexRoute
  '/swap-history/': typeof SwapHistoryIndexRoute
  '/swap/': typeof SwapIndexRoute
  '/burn/detail/$address': typeof BurnDetailAddressRoute
  '/swap/detail/$address': typeof SwapDetailAddressRoute
  '/admin/whitelist-token/': typeof AdminWhitelistTokenIndexRoute
  '/admin/whitelist-user/': typeof AdminWhitelistUserIndexRoute
  '/admin/burn/detail/$address': typeof AdminBurnDetailAddressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity-history'
    | '/burn'
    | '/my-create-pools'
    | '/my-dashboard'
    | '/my-participated-pools'
    | '/pair-list'
    | '/personal-info-settings'
    | '/settings'
    | '/support'
    | '/swap-history'
    | '/swap'
    | '/burn/detail/$address'
    | '/swap/detail/$address'
    | '/admin/whitelist-token'
    | '/admin/whitelist-user'
    | '/admin/burn/detail/$address'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity-history'
    | '/burn'
    | '/my-create-pools'
    | '/my-dashboard'
    | '/my-participated-pools'
    | '/pair-list'
    | '/personal-info-settings'
    | '/settings'
    | '/support'
    | '/swap-history'
    | '/swap'
    | '/burn/detail/$address'
    | '/swap/detail/$address'
    | '/admin/whitelist-token'
    | '/admin/whitelist-user'
    | '/admin/burn/detail/$address'
  id:
    | '__root__'
    | '/'
    | '/activity-history/'
    | '/burn/'
    | '/my-create-pools/'
    | '/my-dashboard/'
    | '/my-participated-pools/'
    | '/pair-list/'
    | '/personal-info-settings/'
    | '/settings/'
    | '/support/'
    | '/swap-history/'
    | '/swap/'
    | '/burn/detail/$address'
    | '/swap/detail/$address'
    | '/admin/whitelist-token/'
    | '/admin/whitelist-user/'
    | '/admin/burn/detail/$address'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityHistoryIndexRoute: typeof ActivityHistoryIndexRoute
  BurnIndexRoute: typeof BurnIndexRoute
  MyCreatePoolsIndexRoute: typeof MyCreatePoolsIndexRoute
  MyDashboardIndexRoute: typeof MyDashboardIndexRoute
  MyParticipatedPoolsIndexRoute: typeof MyParticipatedPoolsIndexRoute
  PairListIndexRoute: typeof PairListIndexRoute
  PersonalInfoSettingsIndexRoute: typeof PersonalInfoSettingsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SupportIndexRoute: typeof SupportIndexRoute
  SwapHistoryIndexRoute: typeof SwapHistoryIndexRoute
  SwapIndexRoute: typeof SwapIndexRoute
  BurnDetailAddressRoute: typeof BurnDetailAddressRoute
  SwapDetailAddressRoute: typeof SwapDetailAddressRoute
  AdminWhitelistTokenIndexRoute: typeof AdminWhitelistTokenIndexRoute
  AdminWhitelistUserIndexRoute: typeof AdminWhitelistUserIndexRoute
  AdminBurnDetailAddressRoute: typeof AdminBurnDetailAddressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swap/': {
      id: '/swap/'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof SwapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swap-history/': {
      id: '/swap-history/'
      path: '/swap-history'
      fullPath: '/swap-history'
      preLoaderRoute: typeof SwapHistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/': {
      id: '/support/'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal-info-settings/': {
      id: '/personal-info-settings/'
      path: '/personal-info-settings'
      fullPath: '/personal-info-settings'
      preLoaderRoute: typeof PersonalInfoSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair-list/': {
      id: '/pair-list/'
      path: '/pair-list'
      fullPath: '/pair-list'
      preLoaderRoute: typeof PairListIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-participated-pools/': {
      id: '/my-participated-pools/'
      path: '/my-participated-pools'
      fullPath: '/my-participated-pools'
      preLoaderRoute: typeof MyParticipatedPoolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-dashboard/': {
      id: '/my-dashboard/'
      path: '/my-dashboard'
      fullPath: '/my-dashboard'
      preLoaderRoute: typeof MyDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-create-pools/': {
      id: '/my-create-pools/'
      path: '/my-create-pools'
      fullPath: '/my-create-pools'
      preLoaderRoute: typeof MyCreatePoolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/burn/': {
      id: '/burn/'
      path: '/burn'
      fullPath: '/burn'
      preLoaderRoute: typeof BurnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity-history/': {
      id: '/activity-history/'
      path: '/activity-history'
      fullPath: '/activity-history'
      preLoaderRoute: typeof ActivityHistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/whitelist-user/': {
      id: '/admin/whitelist-user/'
      path: '/admin/whitelist-user'
      fullPath: '/admin/whitelist-user'
      preLoaderRoute: typeof AdminWhitelistUserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/whitelist-token/': {
      id: '/admin/whitelist-token/'
      path: '/admin/whitelist-token'
      fullPath: '/admin/whitelist-token'
      preLoaderRoute: typeof AdminWhitelistTokenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swap/detail/$address': {
      id: '/swap/detail/$address'
      path: '/swap/detail/$address'
      fullPath: '/swap/detail/$address'
      preLoaderRoute: typeof SwapDetailAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/burn/detail/$address': {
      id: '/burn/detail/$address'
      path: '/burn/detail/$address'
      fullPath: '/burn/detail/$address'
      preLoaderRoute: typeof BurnDetailAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/burn/detail/$address': {
      id: '/admin/burn/detail/$address'
      path: '/admin/burn/detail/$address'
      fullPath: '/admin/burn/detail/$address'
      preLoaderRoute: typeof AdminBurnDetailAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityHistoryIndexRoute: ActivityHistoryIndexRoute,
  BurnIndexRoute: BurnIndexRoute,
  MyCreatePoolsIndexRoute: MyCreatePoolsIndexRoute,
  MyDashboardIndexRoute: MyDashboardIndexRoute,
  MyParticipatedPoolsIndexRoute: MyParticipatedPoolsIndexRoute,
  PairListIndexRoute: PairListIndexRoute,
  PersonalInfoSettingsIndexRoute: PersonalInfoSettingsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SupportIndexRoute: SupportIndexRoute,
  SwapHistoryIndexRoute: SwapHistoryIndexRoute,
  SwapIndexRoute: SwapIndexRoute,
  BurnDetailAddressRoute: BurnDetailAddressRoute,
  SwapDetailAddressRoute: SwapDetailAddressRoute,
  AdminWhitelistTokenIndexRoute: AdminWhitelistTokenIndexRoute,
  AdminWhitelistUserIndexRoute: AdminWhitelistUserIndexRoute,
  AdminBurnDetailAddressRoute: AdminBurnDetailAddressRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
