/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SwapIndexRouteImport } from './routes/swap/index'
import { Route as SwapHistoryIndexRouteImport } from './routes/swap-history/index'
import { Route as SupportIndexRouteImport } from './routes/support/index'
import { Route as StakingIndexRouteImport } from './routes/staking/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as PersonalInfoSettingsIndexRouteImport } from './routes/personal-info-settings/index'
import { Route as PairListIndexRouteImport } from './routes/pair-list/index'
import { Route as MyParticipatedPoolsIndexRouteImport } from './routes/my-participated-pools/index'
import { Route as MyDashboardIndexRouteImport } from './routes/my-dashboard/index'
import { Route as MyCreatePoolsIndexRouteImport } from './routes/my-create-pools/index'
import { Route as MyActivityIndexRouteImport } from './routes/my-activity/index'
import { Route as BurnIndexRouteImport } from './routes/burn/index'
import { Route as ActivityHistoryIndexRouteImport } from './routes/activity-history/index'
import { Route as SwapCreateIndexRouteImport } from './routes/swap/create/index'
import { Route as BurnCreateIndexRouteImport } from './routes/burn/create/index'
import { Route as SwapDetailAddressRouteImport } from './routes/swap/detail/$address'
import { Route as StakingDetailAddressRouteImport } from './routes/staking/detail/$address'
import { Route as BurnDetailAddressRouteImport } from './routes/burn/detail/$address'
import { Route as PairDetailChainIdTokenInTokenOutRouteImport } from './routes/pair-detail/$chainId/$tokenIn/$tokenOut'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SwapIndexRoute = SwapIndexRouteImport.update({
  id: '/swap/',
  path: '/swap/',
  getParentRoute: () => rootRouteImport,
} as any)
const SwapHistoryIndexRoute = SwapHistoryIndexRouteImport.update({
  id: '/swap-history/',
  path: '/swap-history/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportIndexRoute = SupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => rootRouteImport,
} as any)
const StakingIndexRoute = StakingIndexRouteImport.update({
  id: '/staking/',
  path: '/staking/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalInfoSettingsIndexRoute =
  PersonalInfoSettingsIndexRouteImport.update({
    id: '/personal-info-settings/',
    path: '/personal-info-settings/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PairListIndexRoute = PairListIndexRouteImport.update({
  id: '/pair-list/',
  path: '/pair-list/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyParticipatedPoolsIndexRoute =
  MyParticipatedPoolsIndexRouteImport.update({
    id: '/my-participated-pools/',
    path: '/my-participated-pools/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MyDashboardIndexRoute = MyDashboardIndexRouteImport.update({
  id: '/my-dashboard/',
  path: '/my-dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCreatePoolsIndexRoute = MyCreatePoolsIndexRouteImport.update({
  id: '/my-create-pools/',
  path: '/my-create-pools/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyActivityIndexRoute = MyActivityIndexRouteImport.update({
  id: '/my-activity/',
  path: '/my-activity/',
  getParentRoute: () => rootRouteImport,
} as any)
const BurnIndexRoute = BurnIndexRouteImport.update({
  id: '/burn/',
  path: '/burn/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityHistoryIndexRoute = ActivityHistoryIndexRouteImport.update({
  id: '/activity-history/',
  path: '/activity-history/',
  getParentRoute: () => rootRouteImport,
} as any)
const SwapCreateIndexRoute = SwapCreateIndexRouteImport.update({
  id: '/swap/create/',
  path: '/swap/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const BurnCreateIndexRoute = BurnCreateIndexRouteImport.update({
  id: '/burn/create/',
  path: '/burn/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const SwapDetailAddressRoute = SwapDetailAddressRouteImport.update({
  id: '/swap/detail/$address',
  path: '/swap/detail/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const StakingDetailAddressRoute = StakingDetailAddressRouteImport.update({
  id: '/staking/detail/$address',
  path: '/staking/detail/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const BurnDetailAddressRoute = BurnDetailAddressRouteImport.update({
  id: '/burn/detail/$address',
  path: '/burn/detail/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const PairDetailChainIdTokenInTokenOutRoute =
  PairDetailChainIdTokenInTokenOutRouteImport.update({
    id: '/pair-detail/$chainId/$tokenIn/$tokenOut',
    path: '/pair-detail/$chainId/$tokenIn/$tokenOut',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity-history': typeof ActivityHistoryIndexRoute
  '/burn': typeof BurnIndexRoute
  '/my-activity': typeof MyActivityIndexRoute
  '/my-create-pools': typeof MyCreatePoolsIndexRoute
  '/my-dashboard': typeof MyDashboardIndexRoute
  '/my-participated-pools': typeof MyParticipatedPoolsIndexRoute
  '/pair-list': typeof PairListIndexRoute
  '/personal-info-settings': typeof PersonalInfoSettingsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/staking': typeof StakingIndexRoute
  '/support': typeof SupportIndexRoute
  '/swap-history': typeof SwapHistoryIndexRoute
  '/swap': typeof SwapIndexRoute
  '/burn/detail/$address': typeof BurnDetailAddressRoute
  '/staking/detail/$address': typeof StakingDetailAddressRoute
  '/swap/detail/$address': typeof SwapDetailAddressRoute
  '/burn/create': typeof BurnCreateIndexRoute
  '/swap/create': typeof SwapCreateIndexRoute
  '/pair-detail/$chainId/$tokenIn/$tokenOut': typeof PairDetailChainIdTokenInTokenOutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity-history': typeof ActivityHistoryIndexRoute
  '/burn': typeof BurnIndexRoute
  '/my-activity': typeof MyActivityIndexRoute
  '/my-create-pools': typeof MyCreatePoolsIndexRoute
  '/my-dashboard': typeof MyDashboardIndexRoute
  '/my-participated-pools': typeof MyParticipatedPoolsIndexRoute
  '/pair-list': typeof PairListIndexRoute
  '/personal-info-settings': typeof PersonalInfoSettingsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/staking': typeof StakingIndexRoute
  '/support': typeof SupportIndexRoute
  '/swap-history': typeof SwapHistoryIndexRoute
  '/swap': typeof SwapIndexRoute
  '/burn/detail/$address': typeof BurnDetailAddressRoute
  '/staking/detail/$address': typeof StakingDetailAddressRoute
  '/swap/detail/$address': typeof SwapDetailAddressRoute
  '/burn/create': typeof BurnCreateIndexRoute
  '/swap/create': typeof SwapCreateIndexRoute
  '/pair-detail/$chainId/$tokenIn/$tokenOut': typeof PairDetailChainIdTokenInTokenOutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity-history/': typeof ActivityHistoryIndexRoute
  '/burn/': typeof BurnIndexRoute
  '/my-activity/': typeof MyActivityIndexRoute
  '/my-create-pools/': typeof MyCreatePoolsIndexRoute
  '/my-dashboard/': typeof MyDashboardIndexRoute
  '/my-participated-pools/': typeof MyParticipatedPoolsIndexRoute
  '/pair-list/': typeof PairListIndexRoute
  '/personal-info-settings/': typeof PersonalInfoSettingsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/staking/': typeof StakingIndexRoute
  '/support/': typeof SupportIndexRoute
  '/swap-history/': typeof SwapHistoryIndexRoute
  '/swap/': typeof SwapIndexRoute
  '/burn/detail/$address': typeof BurnDetailAddressRoute
  '/staking/detail/$address': typeof StakingDetailAddressRoute
  '/swap/detail/$address': typeof SwapDetailAddressRoute
  '/burn/create/': typeof BurnCreateIndexRoute
  '/swap/create/': typeof SwapCreateIndexRoute
  '/pair-detail/$chainId/$tokenIn/$tokenOut': typeof PairDetailChainIdTokenInTokenOutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity-history'
    | '/burn'
    | '/my-activity'
    | '/my-create-pools'
    | '/my-dashboard'
    | '/my-participated-pools'
    | '/pair-list'
    | '/personal-info-settings'
    | '/settings'
    | '/staking'
    | '/support'
    | '/swap-history'
    | '/swap'
    | '/burn/detail/$address'
    | '/staking/detail/$address'
    | '/swap/detail/$address'
    | '/burn/create'
    | '/swap/create'
    | '/pair-detail/$chainId/$tokenIn/$tokenOut'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity-history'
    | '/burn'
    | '/my-activity'
    | '/my-create-pools'
    | '/my-dashboard'
    | '/my-participated-pools'
    | '/pair-list'
    | '/personal-info-settings'
    | '/settings'
    | '/staking'
    | '/support'
    | '/swap-history'
    | '/swap'
    | '/burn/detail/$address'
    | '/staking/detail/$address'
    | '/swap/detail/$address'
    | '/burn/create'
    | '/swap/create'
    | '/pair-detail/$chainId/$tokenIn/$tokenOut'
  id:
    | '__root__'
    | '/'
    | '/activity-history/'
    | '/burn/'
    | '/my-activity/'
    | '/my-create-pools/'
    | '/my-dashboard/'
    | '/my-participated-pools/'
    | '/pair-list/'
    | '/personal-info-settings/'
    | '/settings/'
    | '/staking/'
    | '/support/'
    | '/swap-history/'
    | '/swap/'
    | '/burn/detail/$address'
    | '/staking/detail/$address'
    | '/swap/detail/$address'
    | '/burn/create/'
    | '/swap/create/'
    | '/pair-detail/$chainId/$tokenIn/$tokenOut'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityHistoryIndexRoute: typeof ActivityHistoryIndexRoute
  BurnIndexRoute: typeof BurnIndexRoute
  MyActivityIndexRoute: typeof MyActivityIndexRoute
  MyCreatePoolsIndexRoute: typeof MyCreatePoolsIndexRoute
  MyDashboardIndexRoute: typeof MyDashboardIndexRoute
  MyParticipatedPoolsIndexRoute: typeof MyParticipatedPoolsIndexRoute
  PairListIndexRoute: typeof PairListIndexRoute
  PersonalInfoSettingsIndexRoute: typeof PersonalInfoSettingsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  StakingIndexRoute: typeof StakingIndexRoute
  SupportIndexRoute: typeof SupportIndexRoute
  SwapHistoryIndexRoute: typeof SwapHistoryIndexRoute
  SwapIndexRoute: typeof SwapIndexRoute
  BurnDetailAddressRoute: typeof BurnDetailAddressRoute
  StakingDetailAddressRoute: typeof StakingDetailAddressRoute
  SwapDetailAddressRoute: typeof SwapDetailAddressRoute
  BurnCreateIndexRoute: typeof BurnCreateIndexRoute
  SwapCreateIndexRoute: typeof SwapCreateIndexRoute
  PairDetailChainIdTokenInTokenOutRoute: typeof PairDetailChainIdTokenInTokenOutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swap/': {
      id: '/swap/'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof SwapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swap-history/': {
      id: '/swap-history/'
      path: '/swap-history'
      fullPath: '/swap-history'
      preLoaderRoute: typeof SwapHistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/': {
      id: '/support/'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staking/': {
      id: '/staking/'
      path: '/staking'
      fullPath: '/staking'
      preLoaderRoute: typeof StakingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal-info-settings/': {
      id: '/personal-info-settings/'
      path: '/personal-info-settings'
      fullPath: '/personal-info-settings'
      preLoaderRoute: typeof PersonalInfoSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair-list/': {
      id: '/pair-list/'
      path: '/pair-list'
      fullPath: '/pair-list'
      preLoaderRoute: typeof PairListIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-participated-pools/': {
      id: '/my-participated-pools/'
      path: '/my-participated-pools'
      fullPath: '/my-participated-pools'
      preLoaderRoute: typeof MyParticipatedPoolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-dashboard/': {
      id: '/my-dashboard/'
      path: '/my-dashboard'
      fullPath: '/my-dashboard'
      preLoaderRoute: typeof MyDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-create-pools/': {
      id: '/my-create-pools/'
      path: '/my-create-pools'
      fullPath: '/my-create-pools'
      preLoaderRoute: typeof MyCreatePoolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-activity/': {
      id: '/my-activity/'
      path: '/my-activity'
      fullPath: '/my-activity'
      preLoaderRoute: typeof MyActivityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/burn/': {
      id: '/burn/'
      path: '/burn'
      fullPath: '/burn'
      preLoaderRoute: typeof BurnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity-history/': {
      id: '/activity-history/'
      path: '/activity-history'
      fullPath: '/activity-history'
      preLoaderRoute: typeof ActivityHistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swap/create/': {
      id: '/swap/create/'
      path: '/swap/create'
      fullPath: '/swap/create'
      preLoaderRoute: typeof SwapCreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/burn/create/': {
      id: '/burn/create/'
      path: '/burn/create'
      fullPath: '/burn/create'
      preLoaderRoute: typeof BurnCreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swap/detail/$address': {
      id: '/swap/detail/$address'
      path: '/swap/detail/$address'
      fullPath: '/swap/detail/$address'
      preLoaderRoute: typeof SwapDetailAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staking/detail/$address': {
      id: '/staking/detail/$address'
      path: '/staking/detail/$address'
      fullPath: '/staking/detail/$address'
      preLoaderRoute: typeof StakingDetailAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/burn/detail/$address': {
      id: '/burn/detail/$address'
      path: '/burn/detail/$address'
      fullPath: '/burn/detail/$address'
      preLoaderRoute: typeof BurnDetailAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair-detail/$chainId/$tokenIn/$tokenOut': {
      id: '/pair-detail/$chainId/$tokenIn/$tokenOut'
      path: '/pair-detail/$chainId/$tokenIn/$tokenOut'
      fullPath: '/pair-detail/$chainId/$tokenIn/$tokenOut'
      preLoaderRoute: typeof PairDetailChainIdTokenInTokenOutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityHistoryIndexRoute: ActivityHistoryIndexRoute,
  BurnIndexRoute: BurnIndexRoute,
  MyActivityIndexRoute: MyActivityIndexRoute,
  MyCreatePoolsIndexRoute: MyCreatePoolsIndexRoute,
  MyDashboardIndexRoute: MyDashboardIndexRoute,
  MyParticipatedPoolsIndexRoute: MyParticipatedPoolsIndexRoute,
  PairListIndexRoute: PairListIndexRoute,
  PersonalInfoSettingsIndexRoute: PersonalInfoSettingsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  StakingIndexRoute: StakingIndexRoute,
  SupportIndexRoute: SupportIndexRoute,
  SwapHistoryIndexRoute: SwapHistoryIndexRoute,
  SwapIndexRoute: SwapIndexRoute,
  BurnDetailAddressRoute: BurnDetailAddressRoute,
  StakingDetailAddressRoute: StakingDetailAddressRoute,
  SwapDetailAddressRoute: SwapDetailAddressRoute,
  BurnCreateIndexRoute: BurnCreateIndexRoute,
  SwapCreateIndexRoute: SwapCreateIndexRoute,
  PairDetailChainIdTokenInTokenOutRoute: PairDetailChainIdTokenInTokenOutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
